### ISSUE TITLE
"keep-fullscreen" has shady-dom issues

### ISSUE THREAD

**Issue by ta1188** [fs-webdev/fs-dialog#105]
The `fs-modal-dialog` and the `fs-anchored-dialog` (when using the `keep-fullscreen` attribute) in shady-dom allows other items, beneath the modal to show on top. 

_Note:_  This doesn't happen when using shadow-dom and doesn't seem to happen when the `keep-fullscreen` is not used.

<img width="1025" alt="screen shot 2018-11-27 at 1 58 51 pm" src="https://user-images.githubusercontent.com/18534488/49111187-ab4a2700-f24c-11e8-9a77-fcc16fdc29f4.png">

**Comment by ta1188** [comment]
What is the recommended way to insert DOM into the globally registered modal? Or can I still use the one I have in the DOM, but somehow register _that_ globally?

**Comment by skye2k2** [comment]
We generally follow the pattern of keeping any dialogs as separate, self-registering components.

Self-registration: https://github.com/fs-webdev/fs-person-page/blob/73244a43bf7f849545bd49109428a8029cb9b3c3/fs-tree-person-delete/fs-tree-person-impedance-dialog.html#L38

Consuming component: https://github.com/fs-webdev/fs-person-page/blob/73244a43bf7f849545bd49109428a8029cb9b3c3/fs-tree-person-delete/fs-tree-person-delete-link.html#L103-L106

**Comment by ta1188** [comment]
That fixed the issue. Thanks
